name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      # 이전 커밋과 이후 커밋 사이의 변경된 파일 추출
      - name: Get modified files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified_files.txt

      # 변경된 파일과 커밋 메시지 추출
      - name: Extract commit messages and modified files
        run: |
          # 커밋 메시지 추출
          git log --pretty=format:"- %s" ${{ github.event.before }}..${{ github.event.after }} > new_commit_messages.txt
          
          # 수정된 파일 목록 확인
          echo "Modified files:"
          cat modified_files.txt
          echo "Commit messages:"
          cat new_commit_messages.txt

      # 웹훅 전송
      - name: Send webhook with modified files and commit messages
        run: |
          modified_files=$(cat modified_files.txt)
          commit_messages=$(cat new_commit_messages.txt)
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}

          curl -v -X POST "https://prod-21.southeastasia.logic.azure.com:443/workflows/4170e84816d5479b8561351ec691e162/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=w_kQ40iVvmJoPBIWK6Iqpk5THr6_TIhABj2HmjIsulQ" \
          -H "Content-Type: application/json" \
          -d '{
                "type": "message",
                "attachments": [
                  {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": null,
                    "content": {
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "type": "AdaptiveCard",
                      "version": "1.2",
                      "body": [
                        {
                            "type": "ColumnSet",
                            "columns": [
                              {
                                "type": "Column",
                                "targetWidth": "atLeast:narrow",
                                "items": [
                                  {
                                    "type": "Image",
                                    "style": "Person",
                                    "url": "https://cdn-icons-png.flaticon.com/512/25/25231.png",
                                    "size": "Small"
                                  }
                                ],
                                "width": "auto"
                              },
                              {
                                "type": "Column",
                                "spacing": "medium",
                                "verticalContentAlignment": "center",
                                "items": [
                                  {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "size": "Large",
                                    "text": "'"$BRANCH_NAME"' 브랜치가 빌드를 시작했습니다!",
                                    "wrap": true
                                  },
                                ],
                                "width": "auto"
                              },
                            ]
                          },
                        {
                          "type": "TextBlock",
                          "weight": "Bolder",
                          "text": "커밋 메시지:",
                          "wrap": true
                        },
                        {
                          "type": "TextBlock",
                          "text": "'"$commit_messages"'",
                          "wrap": true
                        },
                      ]
                    }
                  }
                ]
              }'
