name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook with dynamic branch name
        run: |
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          curl -X POST https://example.com/webhook \
          -H "Content-Type: application/json" \
          -d '{
                "attachments": [
                  {
                    "contentType": "object",
                    "content": {
                      "type": "AdaptiveCard",
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "version": "1.2",
                      "body": [
                        {
                          "type": "TextBlock",
                          "size": "Medium",
                          "weight": "Bolder",
                          "text": "{{ notification.title | escape(strategy=\"json\") }}"
                        },
                        {
                          "type": "TextBlock",
                          "text": "Dependency-Track",
                          "weight": "Bolder",
                          "spacing": "Medium"
                        },
                        {
                          "type": "TextBlock",
                          "text": "{{ timestamp }}",
                          "spacing": "None"
                        },
                        {
                          "type": "Image",
                          "url": "https://raw.githubusercontent.com/DependencyTrack/branding/master/dt-logo-symbol-blue-background.png",
                          "size": "Small",
                          "spacing": "Medium"
                        },
                        {
                          "type": "FactSet",
                          "facts": [
                            {
                              "title": "VulnID",
                              "value": "{{ subject.vulnerability.vulnId | escape(strategy=\"json\") }}"
                            },
                            {
                              "title": "Severity",
                              "value": "{{ subject.vulnerability.severity | escape(strategy=\"json\") }}"
                            },
                            {
                              "title": "Source",
                              "value": "{{ subject.vulnerability.source | escape(strategy=\"json\") }}"
                            },
                            {
                              "title": "Component",
                              "value": "{{ subject.component.toString | escape(strategy=\"json\") }}"
                            }
                          ]
                        },
                        {
                          "type": "TextBlock",
                          "text": "{{ notification.content | escape(strategy=\"json\") }}",
                          "wrap": true
                        }
                      ]
                    }
                  }
                ]
              }'
