name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook with dynamic branch name
        run: |
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          curl -X POST https://example.com/webhook \
          -H "Content-Type: application/json" \
          -d '{
                "type": "AdaptiveCard",
                "version": "1.2",
                "body": [
                  {
                    "type": "Container",
                    "items": [
                      {
                        "type": "TextBlock",
                        "text": "",
                        "weight": "Bolder",
                        "size": "Large",
                        "color": "Attention",
                        "horizontalAlignment": "Center"
                      },
                      {
                        "type": "TextBlock",
                        "text": "Summary: ",
                        "wrap": true,
                        "size": "Medium",
                        "weight": "Bolder"
                      },
                      {
                        "type": "TextBlock",
                        "text": "",
                        "wrap": true,
                        "size": "Medium",
                        "weight": "Bolder"
                      },
                      {
                        "type": "ActionSet",
                        "actions": [
                          {
                            "type": "Action.OpenUrl",
                            "title": "",
                            "url": ""
                          }
                        ],
                        "spacing": "Medium"
                      }
                    ],
                    "style": "emphasis",
                    "bleed": true
                  }
                ]
              }'
