name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook with dynamic branch name
        run: |
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          curl -X POST https://example.com/webhook \
          -H "Content-Type: application/json" \
          -d '{
                "type": "AdaptiveCard",
                "body": [
                    "type": "TextBlock",
                    "size": "medium",
                    "text": "Test"
                    ]
              }'
