name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook with dynamic branch name
        run: |
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          curl -X POST https://example.com/webhook \
          -H "Content-Type: application/json" \
          -d '{
                "type": "object",
                "attachments": [
                  {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "content": {
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "type": "AdaptiveCard",
                      "version": "1.4",
                      "body": [
                        {
                          "type": "TextBlock",
                          "text": "AdaptiveCard Example",
                          "weight": "Bolder",
                          "size": "Large",
                          "color": "Attention",
                          "horizontalAlignment": "Center"
                        },
                        {
                          "type": "TextBlock",
                          "text": "Summary: ",
                          "wrap": true,
                          "size": "Medium",
                          "weight": "Bolder"
                        },
                        {
                          "type": "TextBlock",
                          "text": "This is a dynamically generated message for the '$BRANCH_NAME' branch.",
                          "wrap": true,
                          "size": "Medium",
                          "weight": "Bolder"
                        },
                        {
                          "type": "ActionSet",
                          "actions": [
                            {
                              "type": "Action.OpenUrl",
                              "title": "View Details",
                              "url": "https://example.com/details"
                            }
                          ],
                          "spacing": "Medium"
                        }
                      ]
                    }
                  }
                ]
              }'
