name: Send Webhook on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Extract all commit messages from the PR merge
        run: |
          # PR에서 머지된 모든 커밋 메시지를 임시 파일에 저장
          git log --pretty=format:"- %s" $GITHUB_SHA~10..$GITHUB_SHA > commit_messages.txt

      - name: 웹훅 보내기
        run: |
          # 파일에서 커밋 메시지 읽어오기
          commit_messages=$(cat commit_messages.txt)
          BRANCH_NAME="${{ github.ref }}"
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          curl -v -X POST "https://prod-21.southeastasia.logic.azure.com:443/workflows/4170e84816d5479b8561351ec691e162/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=w_kQ40iVvmJoPBIWK6Iqpk5THr6_TIhABj2HmjIsulQ" \
          -H "Content-Type: application/json" \
          -d '{
                "type": "message",
                "attachments": [
                  {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": null,
                    "content": {
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "type": "AdaptiveCard",
                      "version": "1.2",
                      "body": [
                          {
                            "type": "ColumnSet",
                            "columns": [
                              {
                                "type": "Column",
                                "targetWidth": "atLeast:narrow",
                                "items": [
                                  {
                                    "type": "Image",
                                    "style": "Person",
                                    "url": "https://cdn-icons-png.flaticon.com/512/25/25231.png",
                                    "size": "Small"
                                  }
                                ],
                                "width": "auto"
                              },
                              {
                                "type": "Column",
                                "spacing": "medium",
                                "verticalContentAlignment": "center",
                                "items": [
                                  {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "size": "Large",
                                    "text": "'"$BRANCH_NAME"' 브랜치가 빌드를 시작했습니다!",
                                    "wrap": true
                                  },
                                ],
                                "width": "auto"
                              },
                            ]
                          },
                          {
                            "type": "TextBlock",
                            "text": "'"$commit_messages"'",
                            "wrap": true
                          }
                      ]
                    }
                  }
                ]
              }'
